### PR TITLE
Public methods for open/close/toggle

### PR DESCRIPTION
**Pull request by alexrabarts**
This pull request adds public methods to allow for programmatic control over the state of the accordion. e.g. to manually open an accordion:

```
<Accordion header={header} content={content} ref="myAccordion" />

this.refs.myAccordion.open();
```

The pull request provides methods for open, close and toggle.

### CODE REVIEW

**Comment by naoufal** [comment]
@alexrabarts can you leave a PR description when the change is finished?

I'll review after that. Thanks!

**Comment by alexrabarts** [comment]
Done. Thanks.

**Comment by naoufal** [comment]
@alexrabarts Sorry about the delay on this—I was sure I had already merged it.  

This change looks good. :+1:

**Comment by naoufal** [comment]
@alexrabarts published on npm.

**Comment by alexrabarts** [comment]
Great, thank you.

**Pull request merged**
